#! /bin/bash
### BEGIN INIT INFO
# Provides:          octopusd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DSL octopus daemon
# Description:       DSL octopus daemon
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE="/var/run/octopusd.pid"
APP_EXEC="/usr/local/bin/octopusd"
DAEMON_NAME="octopusd"

case "$1" in
    start)
	log_daemon_msg "Starting DSL octopus daemon" $DAEMON_NAME || true
	if start-stop-daemon --make-pidfile --background --start --quiet --oknodo --pidfile $PIDFILE --exec $APP_EXEC; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
        ;;
    stop)
	log_daemon_msg "Stopping DSL octopus daemon" "doord" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
        ;;
    status)
	status_of_proc -p $PIDFILE $APP_EXEC doord && exit 0 || exit $?
        ;;
    restart)
	log_daemon_msg "Restarting DSL octopus daemon" $DAEMON_NAME || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	if start-stop-daemon --make-pidfile --background --start --quiet --oknodo --pidfile $PIDFILE --exec $APP_EXEC; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
        ;;
  *)

esac
exit 0
