#!/bin/bash
#
#	usage: ./door {add, start, stop, restart}
#
#	turns door.py into a daemon
#
if [ $1 == "add" ]; then
    ./door.py add
    sudo /etc/init.d/doord restart
else
    sudo /etc/init.d/doord $1
fi
