#! /bin/bash
### BEGIN INIT INFO
# Provides:          doord
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

APP_PATH=/home/pi/door/dootdoorlock
PYTHON=/usr/local/bin/python3
APP_NAME=door.py

PATH=/usr/local/bin

start() {
    cd $APP_PATH
    zdaemon -d -p ./$APP_NAME start
}

stop() {
    cd $APP_PATH
    zdaemon -d -p ./$APP_NAME stop
}

check_status() {
    cd $APP_PATH
    zdaemon -d -p ./$APP_NAME status
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        check_status
        ;;
  restart)
        stop
        start
        ;;
  *)

esac
exit 0
